### ISSUE TITLE
Guideline for protocol identifiers, clarify endian-ness

### ISSUE THREAD

**Issue by vermorel** [Lokad/Terab#19]
The endian-ness of values presented in the guideline must be clarified.

**Comment by jcramer** [comment]
It is not clear to us what is meant by the following statement found within the protocol identifiers spec: 

> However, values pushed on the Script stack are expected to be encoded in little endian.

We have reserved the prefix `0x00534c50` (SLP in ascii).  We plan to use the following script to push this data following op_return `0400534c50` so that the op_return message contains as "SLP" in some block explorers and op_return tools.  However, the above-quoted sentence from the specification has led us to believe that you are actually asking us to reverse the order of the bytes, so we should push `04504c5300`.  Please advise which script should be pushed for us and we suggest providing a concrete example in the spec instead of just the placeholder `[protocol_id]`.

**Comment by vermorel** [comment]
For the reference https://en.wikipedia.org/wiki/Endianness#/media/File:Little-Endian.svg

I will add an example. Thank you very much for your attentive follow-up.

**Comment by vermorel** [comment]
I am closing the case, but don't hesitate to re-open if needed. Thanks!

**Comment by markblundeberg** [comment]
Hey, I don't mean to re-open the issue but just wanted to add a comment here. It looks like some other folks might have misinterpreted the endianness too:

0x00004b50 little endian encode == ascii 'PK\0\0' .. maybe they wanted '\0\0KP' for Keoken Platform.

0x00584350 little endian encode == ascii 'PCX\0' .. maybe they wanted '\0XCP' for Counterparty cash.

0x00555354 little endian encode == ascii 'TSU\0' .. maybe they wanted '\0UST' for UniSOT.

etc.

It might be good to check if they have actually made any transactions and which byte array they actually push. If backwards, I would suggest they re-register withe the correct little-endian-decoded integer --- however consider '\0XCP' which would be 0x50435800, and the lokad standard forbids this high of a number for some reason. What to do?

(Perhaps for new registrations, also list the byte array beside the numeric value so registrants know what they're getting :-) .)

**Comment by vermorel** [comment]
Hi Mark, thanks for the insights! Very busy days for me. If you could reach out to those folks this would be very appreciated. Thanks!

**Comment by jcramer** [comment]
@jsmith-dev Are you aware of this?
