### ISSUE TITLE
Adding RedirectUrl column to protocols.csv

### ISSUE THREAD

**Issue by jcramer** [Lokad/Terab#6]
It will not be possible for the blockchain explorers to implement all of these protocols, but they could automatically generate a redirect button to redirect to the protocol's main site including the TXN id within the URL.  The redirected site can then display the desired experience of the protocol.

Maybe this was already one intent of all of this, so I'm just saying a `TxnRedirectUrl` column maybe should be added with a common placeholder that can be replaced programmatically by a blockchain explorer (e.g., `simpleledger.cash/txn/{txn_id}` where `{txn_id} would be automatically replaced).

**Comment by vermorel** [comment]
Nice idea! I like it. Rather than update the specification incrementally, I will try to collect the good ideas, and have them pushed to the guideline in batch. It may take a few weeks. It would help me a lot if you could reach out to the other protocol developers to probe them about this idea and see if they have angles to make it better for their own respective use case. Don't hesitate to use the folks listed in `protocols.csv` as the start point of your investigation :-)

**Comment by jcramer** [comment]
@adrienbien154 @eamesyi @thezillia @kosinusbch @shravan-shandilya 

Is this `TxnRedirectUrl` something that would also benefit your protocols?  It might be just a little effort to create the extra endpoint on your server, but this would make it much easier for any blockchain explorer to integrate all of our registered OP_RETURN protocols together.

**Comment by shravan-shandilya** [comment]
@jcramer That's a nice thing to have. I can think of some benefits specific to our protocol.

**Comment by eamesyi** [comment]
Hi James, I like it. Thumbs up from me. @jcramer

**Comment by vermorel** [comment]
Strong agreement on this. Let's wrap this as `TxidRedirectUrl` to be very specific on the intent and nature of the URL. I will make this part of the guideline.

**Comment by vermorel** [comment]
Done!
